version: '3'
services:
  docker-deploy-example:
    build:
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
      context: .
    image: docker-deploy-example
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
