version: '3'
services:
  docker-deploy-example:
    build: .
    image: docker-deploy-example
    args:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
